# Generated by Django 5.0.6 on 2024-09-05 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 20, 47, 45, 968707)),
        ),
    ]
