# Generated by Django 5.0.6 on 2024-09-05 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 22, 34, 50, 402615)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
